services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - php
    networks:
      - async-image-processor-network

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    depends_on:
      - db
      - redis
    networks:
      - async-image-processor-network

  worker:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php_worker
    restart: unless-stopped
    command: php /var/www/app/artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/var/www/app:delegated
    depends_on:
      - redis
      - db
    networks:
      - async-image-processor-network

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: async-image-processor
      MYSQL_USER: uek
      MYSQL_PASSWORD: uek
      MYSQL_ROOT_PASSWORD: uek-root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data:/var/lib/mysql
    networks:
      - async-image-processor-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - async-image-processor-network

networks:
  async-image-processor-network:
    driver: bridge
